#!/usr/bin/env python2.5

from optparse import OptionParser
import commands

usage = "usage: %prog [options] startframe endframe input.#.ext output.#.ext"
parser = OptionParser(usage);
parser.add_option("-f", "--fps", dest="fps", default='24', help="Set the frames per second, default is 24.");
parser.add_option("-p", "--padding", dest="padding", default='4', help="Set the frame padding, default is 4.");
parser.add_option("-i", "--initframe", dest="initframe", default='0', help="Initial/first frame of the sim. This is where sim time == 0, default is 0.");
parser.add_option("-s", "--starttime", dest="starttime", default='0', help="Starting time of the sim on the initial sim frame, default is 0.");
parser.add_option("-b", "--bodyname", dest="bodyname", default='trimesh', help="Name for the naiad body, default is 0.");
parser.add_option("-v", "--verbose", dest="verbose", default='1', help="Verbosity level, default is 1.");


(options, args) = parser.parse_args();
#print args
#print options
if len(args) != 4:
	parser.error("incorrect number of arguments");
	

padding = int(options.padding);
fps = float(options.fps);
starttime = float(options.starttime);
firstframe = int(options.initframe);
bodyname = options.bodyname;
verbosity = options.verbose;

startframe = int(args[0]);
endframe = int(args[1]);
inputseq = args[2];
outputseq = args[3];

timestep = 1 / fps;
print timestep
print "Convert sequence from %s to %s using frame range %d to %d at fps %f" % (inputseq, outputseq, startframe, endframe, fps)

for i in range(startframe, endframe+1):
	padstr = "%0"+str(padding)+"d";
	padded_frame = padstr % i
	#print "converting frame: ", padded_frame

	inputfile = inputseq.replace("#", padded_frame);
	outputfile = outputseq.replace("#", padded_frame);
	curtime = (i - firstframe)*timestep + starttime;
	print "##################################"
	print "frame: %d time: %f " % (i, curtime)

	cmd = "geo2emp -b %s -v %s -t %f %s %s" % (bodyname, verbosity, curtime, inputfile, outputfile);
	# do it
	print cmd + "\n"
	status = commands.getstatusoutput(cmd);
	print status[1]
	if status[0] != 0:
		print "\n !!!!! ERROR on frame: %d !!!!! \n" % i;
	


