#!/bin/bash

rm -rf $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH
mkdir  $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH
cd     $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH

mkdir debug2011
mkdir debug2012

mkdir release2011
mkdir release2012

# all plugins linking to 2011 versions
cd $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH/debug2011
cmake -DCMAKE_BUILD_TYPE=DEBUG -DMAYA_INSTALL_PATH="C:\Program Files\Autodesk\Maya2011" -DMAYA_VERSION=2011 -DCMAKE_INSTALL_PREFIX=$NAIAD_PATH $DEV_ROOT_NBUDDIES -G "Visual Studio 10 Win64"

# all plugins linking to 2012 versions
cd $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH/debug2012
cmake -DCMAKE_BUILD_TYPE=DEBUG -DMAYA_INSTALL_PATH="C:\Program Files\Autodesk\Maya2012" -DMAYA_VERSION=2012 -DCMAKE_INSTALL_PREFIX=$NAIAD_PATH $DEV_ROOT_NBUDDIES -G "Visual Studio 10 Win64"

# all plugins linking to 2011 versions
cd $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH/release2011
cmake -DCMAKE_BUILD_TYPE=RELEASE -DMAYA_INSTALL_PATH="C:\Program Files\Autodesk\Maya2011" -DMAYA_VERSION=2011 -DCMAKE_INSTALL_PREFIX=$NAIAD_PATH $DEV_ROOT_NBUDDIES -G "Visual Studio 10 Win64"

# all plugins linking to 2012 versions
cd $DEV_ROOT_NBUDDIES/stage-$EM_PLAT-$EM_ARCH/release2012
cmake -DCMAKE_BUILD_TYPE=RELEASE -DMAYA_INSTALL_PATH="C:\Program Files\Autodesk\Maya2012" -DMAYA_VERSION=2012 -DCMAKE_INSTALL_PREFIX=$NAIAD_PATH $DEV_ROOT_NBUDDIES -G "Visual Studio 10 Win64"
